### PR TITLE
Added support for the new wakatime api key format

### LINKED ISSUE #23: MS Office Add-in API Key Formatting
The current implementation of WakaTime MS Office add-ins do not accept the API key in [waka__***...] format. In order for the API key to be accepted by the Office add-in, the "waka__" prefix needs to be stripped leaving the rest of the API key.

### PR DESCRIPTION
**Pull request by charveey**
Trying to fix #23 #25 regarding the new api format

### CODE REVIEW

**Comment by charveey** [comment]
I forgot to backport the fixes to Excel and Powerpoint. It's done now.

**Comment by ankuyucu** [comment]
Hello. Thank you for your work. I have completed the tasks you instructed, but they are not showing up in the indicator panel or plugin status.

**Comment by charveey** [comment]
> Hello. Thank you for your work. I have completed the tasks you instructed, but they are not showing up in the indicator panel or plugin status.

I have the same problem but I haven't figured out why it doesn't work yet. The log file is empty. See #24
Did it work before?

**Comment by charveey** [comment]
I don't have my computer with me right now but I suspect the use of an old dependency to be responsible.

First of all, can you check if the PowerPoint addin works. It uses version 2.2.0  of the WakaTime.Shared.ExtensionUtils while Excel and Word use version 2.1.0

Secondly, can you try to compile with the latest version on WakaTime.Shared.ExtensionUtils : version 4.1.0 to see if it makes a difference?

[See packages.config](https://github.com/wakatime/office-wakatime/blob/master/WordWakaTimeAddin/packages.config#25)

**Comment by muety** [comment]
Any updates on this?

**Comment by charveey** [comment]
I unfortunately can't do much more. My C# knowledge is fairly limited, and the Office add-ons use a different logic than the one used by the other apps.

**Comment by muety** [comment]
What is exactly is still missing here?

**Comment by charveey** [comment]
For a reason I was not able to identify, the plugin status doesn't show up on the web dashboard and the activity is not tracked. My PR only made the plugins compatible with the new API format (with the waka_ prefix).

And I also noticed that the Office add-ons don't use the newer version of wakatime-cli. See #17

**Comment by charveey** [comment]
And I also noticed that the Office add-ons don't use the newer version of wakatime-cli

**Comment by muety** [comment]
I see, so this is actually about the new "API key format", rather than a new "API format", correct? So there is probably a deeper rooted issue, why statistics are not showing up in WakaTime than just the API key. But can we merge this anyway, because shouldn't hurt, @ankuyucu?

**Comment by hexaaagon** [comment]
any new update?

**Comment by alanhamlett** [comment]
Fixed with #31.

**Pull request closed without merging**
